import { db } from "@/lib/db";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ReconciliationEngine } from "@/components/accounting/reconciliation-engine";
import { FileText } from "lucide-react";
import { enforceRoleAccess } from "@/lib/auth-guard";

export default async function AccountingPage() {
  const { member, isAuthorized, UnauthorizedNode } = await enforceRoleAccess(["OWNER", "ACCOUNTANT"]);
  if (!isAuthorized || !member) return UnauthorizedNode;

  // Fetch recent ledgers
  const ledgers = await db.ledgerEntry.findMany({
    where: { orgId: member.orgId },
    orderBy: { createdAt: "desc" },
    take: 100,
  });

  // Calculate generic balances for UI (Mockup logic for DB values)
  const salesRevenue = ledgers.filter(l => l.account === "SALES_REVENUE" && l.type === "CREDIT").reduce((acc, l) => acc + l.amount, 0);
  const totalAr = ledgers.filter(l => l.account === "ACCOUNTS_RECEIVABLE").reduce((acc, l) => l.type === "DEBIT" ? acc + l.amount : acc - l.amount, 0);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Accounting & General Ledger</h1>
        <p className="text-zinc-500">Double-entry logs automatically generated by GSTSwift events.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
        <div className="p-6 border rounded-xl bg-white dark:bg-zinc-950 shadow-sm">
          <p className="text-sm text-zinc-500 font-medium">Sales Revenue (YTD)</p>
          <p className="text-3xl font-bold mt-2">₹{salesRevenue.toLocaleString("en-IN", { minimumFractionDigits: 2 })}</p>
        </div>
        <div className="p-6 border rounded-xl bg-white dark:bg-zinc-950 shadow-sm">
          <p className="text-sm text-zinc-500 font-medium">Accounts Receivable</p>
          <p className="text-3xl font-bold mt-2">₹{totalAr.toLocaleString("en-IN", { minimumFractionDigits: 2 })}</p>
        </div>
        <div className="p-6 border rounded-xl bg-indigo-50 dark:bg-indigo-950/20 border-indigo-100 dark:border-indigo-900 shadow-sm">
          <p className="text-sm text-indigo-800 dark:text-indigo-400 font-bold">GST Portal Reporting</p>
          <p className="text-xs text-indigo-600 mt-2 mb-4">Export GSTR-1 JSON precisely formatted for the 2026 CBIC offline tool.</p>
          <a href="/api/reports/gstr1" download>
            <button className="w-full mb-2 text-xs font-semibold px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 transition">
              Download GSTR-1 JSON
            </button>
          </a>
          <a href="/api/export/ledger" target="_blank" rel="noopener noreferrer">
            <button className="w-full flex justify-center items-center text-xs font-semibold px-4 py-2 bg-white text-indigo-700 border border-indigo-200 rounded-md hover:bg-indigo-50 transition">
               <FileText className="w-4 h-4 mr-2" /> Download CA Ledger (CSV)
            </button>
          </a>
        </div>
      </div>

      <Tabs defaultValue="ledgers" className="space-y-4">
        <TabsList>
          <TabsTrigger value="ledgers">General Ledger</TabsTrigger>
          <TabsTrigger value="reconciliation">Bank Reconciliation</TabsTrigger>
        </TabsList>

        <TabsContent value="ledgers" className="border rounded-md bg-white dark:bg-zinc-950 shadow-sm overflow-hidden">
          <Table>
            <TableHeader className="bg-zinc-50 dark:bg-zinc-900/50">
              <TableRow>
                <TableHead>Date / Time</TableHead>
                <TableHead>Account</TableHead>
                <TableHead>Reference</TableHead>
                <TableHead className="text-right">Debit</TableHead>
                <TableHead className="text-right">Credit</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {ledgers.map((entry) => (
                <TableRow key={entry.id}>
                  <TableCell className="text-xs text-zinc-500">
                    {entry.createdAt.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}
                  </TableCell>
                  <TableCell>
                    <Badge variant="outline" className={`font-mono ${entry.account.includes('GST') ? 'bg-amber-50 text-amber-700 border-amber-200' : 'bg-slate-50' }`}>
                      {entry.account}
                    </Badge>
                  </TableCell>
                  <TableCell>
                    <span className="font-mono text-xs">{entry.referenceId && `Ref: ${entry.referenceId.slice(-8)}`}</span>
                  </TableCell>
                  <TableCell className="text-right font-medium">
                    {entry.type === "DEBIT" ? `₹${entry.amount.toLocaleString("en-IN", { minimumFractionDigits: 2 })}` : "-"}
                  </TableCell>
                  <TableCell className="text-right font-medium">
                    {entry.type === "CREDIT" ? `₹${entry.amount.toLocaleString("en-IN", { minimumFractionDigits: 2 })}` : "-"}
                  </TableCell>
                </TableRow>
              ))}
              {ledgers.length === 0 && (
                <TableRow>
                  <TableCell colSpan={5} className="h-24 text-center text-zinc-500">
                    No ledger entries created yet. Generate an invoice to see automatic double-entry records.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </TabsContent>

        <TabsContent value="reconciliation">
           <ReconciliationEngine orgId={member.orgId} />
        </TabsContent>
      </Tabs>
    </div>
  );
}
