import { db } from "@/lib/db";
import { auth } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ShieldAlert, ShieldCheck, Trash2 } from "lucide-react";
import { RoleForm } from "./role-form";
import { deleteRolePolicy } from "./actions";

export default async function RBACDashboard() {
  const { userId } = await auth();
  if (!userId) redirect("/sign-in");

  const member = await db.organizationMember.findFirst({
    where: { userId },
    include: { organization: { include: { rolePolicies: true } } }
  });

  if (!member || member.role !== "OWNER") {
    return (
      <div className="flex items-center justify-center p-12 h-full">
        <Card className="max-w-md w-full text-center">
          <CardHeader>
            <CardTitle>Unauthorized Access</CardTitle>
            <CardDescription className="pt-2">
              Role-Based Access Control matrix is restricted to the Organization Owner.
            </CardDescription>
          </CardHeader>
        </Card>
      </div>
    );
  }

  const policies = member.organization.rolePolicies || [];

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Identity & Access Management</h1>
        <p className="text-zinc-500">Construct complex zero-trust Role clusters completely decoupled from the native engine.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="md:col-span-2 space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2"><ShieldCheck className="w-5 h-5 text-emerald-500" /> Active SaaS Policies</CardTitle>
              <CardDescription>Custom authorization vectors generated by your Tenant.</CardDescription>
            </CardHeader>
            <CardContent>
              {policies.length === 0 ? (
                <div className="text-center p-6 bg-zinc-50 dark:bg-zinc-900 border border-dashed rounded-lg text-sm text-zinc-500">
                  No custom policies constructed yet. Employees default to internal fallback arrays.
                </div>
              ) : (
                <div className="space-y-4">
                  {policies.map(policy => {
                    const parsedPerms = JSON.parse(policy.permissions);
                    return (
                      <div key={policy.id} className="p-4 border rounded-lg bg-zinc-50/50 dark:bg-zinc-900/20 flex flex-col sm:flex-row gap-4 sm:items-center justify-between">
                        <div>
                          <h3 className="font-bold tracking-tight">{policy.roleName}</h3>
                          <div className="flex flex-wrap gap-1 mt-2">
                            {parsedPerms.map((node: string) => (
                              <Badge key={node} variant={node.includes("DELETE") ? "destructive" : "secondary"} className="text-[10px]">
                                {node}
                              </Badge>
                            ))}
                            {parsedPerms.length === 0 && <span className="text-xs text-zinc-500 italic">No privileges granted.</span>}
                          </div>
                        </div>
                        <form action={async () => { "use server"; await deleteRolePolicy(policy.id); }}>
                          <Button variant="ghost" size="sm" type="submit" className="text-rose-500 hover:text-rose-600 hover:bg-rose-50">
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </form>
                      </div>
                    );
                  })}
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        <div className="md:col-span-1">
          <RoleForm />
        </div>
      </div>
    </div>
  );
}
